{{- if and .Values.database.enabled 
           .Values.documentLifecycle.bulkDocumentDeletionEnabled
           .Values.documentLifecycle.expirationJob.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "document-engine.fullname" . }}-expire
  labels:
    {{- include "document-engine.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.documentLifecycle.expirationJob.schedule }}
  startingDeadlineSeconds: {{ .Values.documentLifecycle.expirationJob.startingDeadlineSeconds }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 1
      activeDeadlineSeconds: {{ .Values.documentLifecycle.expirationJob.activeDeadlineSeconds }}
      ttlSecondsAfterFinished: {{ .Values.documentLifecycle.expirationJob.ttlSecondsAfterFinished }}
      template:
        metadata:
          {{- with .Values.documentLifecycle.expirationJob.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          labels:
          {{- include "document-engine.expirationSelectorLabels" . | nindent 12 }}
          {{- with .Values.documentLifecycle.expirationJob.podLabels }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
        spec:
          restartPolicy: Never
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.documentLifecycle.expirationJob.serviceAccountName }}
          serviceAccountName: {{ . }}
          {{- end }}
          containers:
            - name: {{ .Chart.Name }}
              env:
                - name: API_AUTH_TOKEN
                  valueFrom:
                    secretKeyRef:
                    {{- if and .Values.apiAuth.externalSecret.name
                              .Values.apiAuth.externalSecret.apiTokenKey }}
                      name: {{ .Values.apiAuth.externalSecret.name }}
                      key: {{ .Values.apiAuth.externalSecret.apiTokenKey }}
                    {{- else }}
                      name: {{ include "document-engine.fullname" . }}
                      key: API_AUTH_TOKEN
                    {{- end }}
              {{- with .Values.documentLifecycle.expirationJob.extraEnvs }}
                {{- toYaml . | nindent 16 }}
              {{- end }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command:
                - /documents-expiration/run.sh
              resources:
                {{- toYaml .Values.documentLifecycle.expirationJob.resources | nindent 16 }}
              volumeMounts:
                - name: cleanup-assets
                  mountPath: /documents-expiration
          volumes:
            - name: cleanup-assets
              configMap:
                name: {{ include "document-engine.fullname" . }}-expire
                defaultMode: 0755
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
